### ISSUE TITLE
Can't catch exception for invalid input

### ISSUE THREAD

**Issue by Petah** [yahoo/dnscache#5]
When using Node's dns library you can catch errors for invalid input:

```
try {
    require('dns').reverse('something wrong', function() {
        console.log('do something');
    });
} catch (e) {
    console.log('some exception happened');
}
```

Output: `some exception happened`

Doing this with dnscache:

```
dns.js:156
      throw errnoException(process._errno, bindingName);
            ^
Error: getHostByAddr ENOTIMP
    at errnoException (dns.js:37:11)
    at Object.query [as reverse] (dns.js:156:13)
    at C:\work\temp\node_modules\dnscache\lib\index.js:285:35
    at Object._onImmediate (C:\work\temp\node_modules\dnscache\lib\cache.js:121:21)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by timbowhite** [comment]
+1

**Comment by timbowhite** [comment]
OK the issue is that you can't catch the errors because dnscache wraps the original method with their own callback.  So a fix could be for dnscache to try/catch in it's wrapper callback, then call the user callback with an error on catch, ie:

```
        // override dns.reverse method
        dns.reverse = function (ip, callback) {
            cache.get('reverse_' + ip, function (error, record) {
                if (record) {
                    callback(error, deepCopy(record));
                } else {
                    try{
                        backup_object.reverse(ip, function (err, addresses) {
                            if (err) {
                                callback(err);
                            } else {
                                cache.set('reverse_' + ip, addresses, function () {
                                    callback(err, deepCopy(addresses));
                                });
                            }
                        });
                    }
                    catch(err){
                        callback(err);
                    }
                }
            });
        };
```

The above change will give you an error in your callback, but won't throw.  It's an easy fix, I'll send in a PR.
